language: python
python:
 - "3.5"
before_install:
 - pip install coveralls
install:
 - pip install -r travis_req.txt
script: 
 - make test
 - coverage run test_rpn.py test
after_success: 
 - COVERALLS_REPO_TOKEN=6st2kcAht0A38q09mkRa1nUOBhVpYjCFE coveralls 

